---
os: Visual Studio 2017

environment:
  CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
  BOOST_ROOT: 'c:\local\boost_1_65_1'
  BOOST_LIBRARYDIR: 'c:\local\boost_1_65_1\lib64-msvc-14.1'

cache:
- vendor\OpenSSL
- c:\local\boost_1_65_1
#- C:\FlexBison

install:
- ps: |
    if (Test-Path "vendor\OpenSSL") {exit}
    .\tools\win32\download-openssl.ps1
- ps: |
    if (Test-Path $env:BOOST_ROOT) {exit}
    Start-FileDownload "https://dl.bintray.com/boostorg/release/1.65.1/binaries/boost_1_65_1-msvc-14.1-64.exe"
    Invoke-Expression ".\boost_1_65_1-msvc-14.1-64.exe /SILENT /DIR=$env:BOOST_ROOT"
#- ps: |
#  if (Test-Path C:\FlexBison) {exit}
#  Start-FileDownload "http://downloads.sourceforge.net/project/winflexbison/win_flex_bison-${env:FLEX_VERSION}.zip"
#  Expand-Archive win_flex_bison-${env:FLEX_VERSION}.zip -DestinationPath "C:\FlexBison"

before_build:
- ps: .\tools\win32\configure.ps1

build_script:
- ps: .\tools\win32\build.ps1

deploy: off